[build]
  command = "CI=false npm run build"
  publish = "build"

[build.environment]
  GENERATE_SOURCEMAP = "false"
  TSC_COMPILE_ON_ERROR = "true"
  ESLINT_NO_DEV_ERRORS = "true"
  DISABLE_ESLINT_PLUGIN = "true"